# Generated by Django 5.0.6 on 2024-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_servicerequest_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
