# Generated by Django 5.0.6 on 2024-06-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_servicerequest_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='resolution',
        ),
    ]
